<center><ins><h1>Extra Polymeric Substance Analysis</h1></ins></center>

<h5>Definition:</h5>
<ul>
    <li>Volatile and Total suspended solids (VSS/TSS) are analytical parameters representing, loosely, the undissolved organic matter in a water sample. More technically, they are water quality parameters and a factor for growth.</li> 
    <li>Formula for TSS G/L = ((DRIEDFILTER_G - EMPTYFILTER_G) / VOLUME_ML) * 1000. TSS can be further used for sludge indices.</li>
    <li>Formula for VSS G/L = ((BURNEDFILTER_G - EMPTYFILTER_G + BLANKFILTER_G) / VOLUME_ML) * 1000.</li>
    <li>Import of only one big data frame .xlsx.</li>
</ul>

<center>
<img src="../images/eps-assays_device.png" alt="Device" width="225" height="300">
<img src="../images/eps-assays_diagram.png" alt="Diagram" width="533" height="300">
<img src="../images/eps-assays_example-graph.png" alt="Example-Graph" width="579" height="300">
</center>

###### **Author:** Cedric Hering-Peter
###### **Address:** AG Schulz / Botantical Institut / Am Botanischen Garten 5 / 24118 Kiel

# Imports

In [1]:
if not data_helper.should_run_eps(CONFIG):
    raise SystemExit(
        "EPS analysis requires the full dataset. "
        "Set data_mode: full in analysis_config.yaml to run this notebook."
    )
import os, sys

WORKSPACE = os.path.abspath(os.path.join(os.getcwd(), ".."))
if WORKSPACE not in sys.path:
    sys.path.insert(0, WORKSPACE)

from scripts import data_helper, plot_helper
import pandas as pd

CONFIG = data_helper.load_config()
META_DATA = data_helper.load_meta_data(CONFIG)
plot_helper.set_config(CONFIG)

# Variables

In [2]:

EXT_VOL = 10

# Show numeric output in decimal format e.g., 2.1514
pd.options.display.float_format = '{:,.4f}'.format

# Raw Data Import

In [3]:
if not data_helper.should_run_eps(CONFIG):
    raise SystemExit(
        "EPS analysis requires the full dataset. "
        "Set data_mode: full in analysis_config.yaml to run this notebook."
    )
# define data path
file_master = [data_helper.get_master_file_path(CONFIG, "eps")]

# import raw data frame
raw_df = data_helper.import_raw_df_from(file_master)
raw_df.sample(5)

,ID,EXPERIMENT_NAME,SAMPLE_NAME,TIME,BIO_REP,TEC_REP,EPS_G,BIOMASS_G,PROTEINS_MG/ML,HEXOSES_MG/ML,PENTOSES_MG/ML,LIPIDS_MG/ML,DNA_MG/ML,R**2-VALUES,NOTE
14,JW230502,RM,EPS_JW,0-h,2,3,NaN,88.9778,0.5400,0.1170,0.1180,0.0173,0.0074,"0.977,0.971,0.980, 0.781, 0",NaN
7,CH231214,RM,EPS_CH,0-h,3,2,NaN,88.9778,0.3172,0.0294,0.0000,0.0000,0.0027,"0.988,0.969,0.832, 0.781, 0",trust pentose values?
37,CH231214,RM,EPS_Grave,0-h,3,2,2.7000,88.9778,NaN,NaN,NaN,NaN,NaN,NaN,-EPS
25,CH231216,RM,EPS_Grave,0-h,1,8,3.2000,88.9778,NaN,NaN,NaN,NaN,NaN,NaN,ET
13,JW230502,RM,EPS_JW,0-h,2,2,NaN,88.9778,0.9090,0.1230,0.1240,0.0244,0.0076,"0.977,0.971,0.980, 0.781, 0",NaN

# Custom Data Cleaning

In [4]:
# Automatic data conversion by pandas
clean_df = raw_df.convert_dtypes()

# Data Calculation

In [10]:
# Initialize new data frame for calculation
calc_df = clean_df.iloc[:, 0:6]


calc_df["EPS_%"] = (clean_df["EPS_G"] / clean_df["BIOMASS_G"]) * 100
calc_df["Biomass_%"] = 100

col_sub = ["PROTEINS_MG/ML", "HEXOSES_MG/ML", "PENTOSES_MG/ML", "LIPIDS_MG/ML", "DNA_MG/ML"]
eps_sum = clean_df[col_sub].sum(axis = 1)
#eps_single = ((clean_df[col_sub] * EXT_VOL) / clean_df[col_sub]) * 100
#print(((clean_df[col_sub] * EXT_VOL) / eps_sum) * 100)
#calc_df["PRO_HEX_PEN_LIP_DNA"] = eps_comp.values.tolist()
#calc_df["PRO_HEX_PEN_LIP_DNA"] * EXT_VOL


calc_df.head()

     0   1   2   3   4   5   6   7   8   9  ...  40  41  42  43  44  \
0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
1  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
2  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
3  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
4  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
5  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
6  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
7  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
8  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
9  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
10 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
11 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
12 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
13 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
14 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
15 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
16 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
17 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
18 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
19 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
20 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
21 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
22 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
23 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
24 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
25 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
26 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
27 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
28 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
29 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
30 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
31 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
32 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
33 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
34 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
35 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
36 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
37 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
38 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
39 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
40 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
41 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
42 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
43 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN
44 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN

    DNA_MG/ML  HEXOSES_MG/ML  LIPIDS_MG/ML  PENTOSES_MG/ML  PROTEINS_MG/ML
0        <NA>           <NA>          <NA>            <NA>            <NA>
1        <NA>           <NA>          <NA>            <NA>            <NA>
2        <NA>           <NA>          <NA>            <NA>            <NA>
3        <NA>           <NA>          <NA>            <NA>            <NA>
4        <NA>           <NA>          <NA>            <NA>            <NA>
5        <NA>           <NA>          <NA>            <NA>            <NA>
6        <NA>           <NA>          <NA>            <NA>            <NA>
7        <NA>           <NA>          <NA>            <NA>            <NA>
8        <NA>           <NA>          <NA>            <NA>            <NA>
9        <NA>           <NA>          <NA>            <NA>            <NA>
10       <NA>           <NA>          <NA>            <NA>            <NA>
11       <NA>           <NA>          <NA>            <NA>            <NA>
12       <NA>           <NA>          <NA>            <NA>            <NA>
13       <NA>           <NA>          <NA>            <NA>            <NA>
14       <NA>           <NA>          <NA>            <NA>            <NA>
15       <NA>           <NA>          <NA>            <NA>            <NA>
16       <NA>           <NA>          <NA>            <NA>            <NA>
17       <NA>           <NA>          <NA>            <NA>            <NA>
18       <NA>           <NA>          <NA>            <NA>            <NA>
19       <NA>           <NA>          <NA>            <NA>            <NA>
20       <NA>           <NA>          <NA>            <NA>            <NA>
21       <NA>           <NA>          <NA>            <NA>            <NA>
22       <NA>           <NA>          <NA>            <NA>            <NA>
23       <NA>           <NA>          <NA>            <NA>            <NA>
24       <NA>           <NA>          <NA>            <NA>            <NA>
25       <NA>           <NA>          <NA>            <NA>            <NA>
26       <NA>           <NA>          <NA>            <NA>            <NA>
27       <NA>           <NA>          <NA>            <NA>            <NA>
28       <NA>           <NA>          <NA>            <NA>            <NA>
29       <NA>           <NA>          <NA>            <NA>            <NA>
30       <NA>           <NA>          <NA>            <NA>            <NA>
31       <NA>           <NA>          <NA>            <NA>            <NA>
32       <NA>           <NA>          <NA>            <NA>            <NA>
33       <NA>           <NA>          <NA>            <NA>            <NA>
34       <NA>           <NA>          <NA>            <NA>            <NA>
35       <NA>           <NA>          <NA>            <NA>            <NA>
36       <NA>           <NA>          <NA>            <NA>            <NA>
37       <NA>           <NA>          <NA>            <NA>            <NA>
38       <NA>           <NA>          <NA>            <NA>            <NA>
39       <NA>           <NA>          <NA>            <NA>            <NA>
40       <NA>           <NA>          <NA>            <NA>            <NA>
41       <NA>           <NA>          <NA>            <NA>            <NA>
42       <NA>           <NA>          <NA>            <NA>            <NA>
43       <NA>           <NA>          <NA>            <NA>            <NA>
44       <NA>           <NA>          <NA>            <NA>            <NA>

[45 rows x 50 columns]

,ID,EXPERIMENT_NAME,SAMPLE_NAME,TIME,BIO_REP,TEC_REP,EPS_%,Biomass_%
0,CH231216,RM,EPS_CH,0-h,1,1,<NA>,100
1,CH231216,RM,EPS_CH,0-h,1,2,<NA>,100
2,CH231216,RM,EPS_CH,0-h,1,3,<NA>,100
3,CH231215,RM,EPS_CH,0-h,2,1,<NA>,100
4,CH231215,RM,EPS_CH,0-h,2,2,<NA>,100

# Data File Export

In [6]:
# Export to raw data .xlsx file into each experiment output folder
unique_exps = META_DATA.EXPERIMENT_NAME.unique()
for exp in unique_exps:
    exp_df = calc_df[calc_df["EXPERIMENT_NAME"] == exp]
    file_name = data_helper.get_output_path(CONFIG, exp, "CH_" + exp + "_Raw-Data.xlsx")
    with pd.ExcelWriter(file_name, engine = "openpyxl", mode = "a", if_sheet_exists = "replace") as writer:
        exp_df.to_excel(writer, sheet_name = "Suspended-Solids", index = False)

# Data Visualization 
#### <url>https://saturncloud.io/blog/how-to-plot-multiple-graphs-in-a-for-loop-with-ipythonjupyter-notebook-and-pandas/</url>

In [7]:
plot_df = calc_df # used data for plot creation

# TODO Possible to show off data with all values without mean() in box plot?
# TODO In theory works but only line plots -> need to progress in udemy course to make clean data visualization
unique_exps = META_DATA.EXPERIMENT_NAME.unique()
for exp in unique_exps:
    # TODO Group into dataframes by experiment_name and bio_rep
    subset = plot_df[plot_df["EXPERIMENT_NAME"] == exp]
    print(subset)
    plt.plot(subset["SAMPLE_NAME"], subset["TSS_G/L"])
    plt.title(f'Graph {exp}')
    plt.xlabel('X-axis label')
    plt.ylabel('Y-axis label')
    plt.show()

# TODO How to investigate multiple plots (click through after running?)

Empty DataFrame
Columns: [ID, EXPERIMENT_NAME, SAMPLE_NAME, TIME, BIO_REP, TEC_REP, EPS_%, Biomass_%]
Index: []

KeyError: 'TSS_G/L'